OnClick methods implemented
expjazz/react_calculator pull request #6
Opened 2020-07-29 14:29 UTC by expjazz

As required, I implemented the handleClick function on the App.js component. However, I think that is unnecessary to re-implement another function in the ButtonPannel that returns the handleClick, so I'm just passing the handleClick function in the props so it finally arrives on the button (it still works).

The result is also displayed in the Display component.

2020-07-30 11:01 UTC, shshamim63 requested changes
## :recycle: Required Changes :recycle: 
___
Hi @expjazz :wave: 
Awesome job :clap: , almost completed the project. Just found a minor issue and it is easy to resolve. Let's fix it.
___
### :spades: Mandatory Changes :spades: 
___
- The +/- is not functioning properly. Please check the comment below to resolve it. 
___
#### Please fix the issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-07-30 11:01 UTC, shshamim63 commented on src/logic/calculate.js
> +    if (dataObject.total) dataObject.total *= -1;
The issue that I mentioned in your previous review is here. So you can work on it a bit to make it work perfectly.
The following sequence is not working properly. 7 + 3 +/- = this is providing -10 but should get 4. while performing browser console provided an error. Cause the display is getting a number instead of a string.
![image](https://user-images.githubusercontent.com/38625956/88914939-3cc13600-d285-11ea-86b5-16cad677acc0.png)
Please resolve it too.

2020-07-30 12:46 UTC, expjazz commented on src/logic/calculate.js
> +    if (dataObject.total) dataObject.total *= -1;
Thanks for pointing this out. I saw in the previous milestone, but since I had created this I did not have time to change. It was a great suggestion.

2020-07-30 12:54 UTC, expjazz commented
- Both bugs were resolved. Thanks @shshamim63

2020-07-30 22:04 UTC, Forison requested changes
## Status:: Require changes❌.
# 🙋‍♂️ Expedito 
#### You have done a good job addressing the issue raised in the previous review, but there are still flaws with the way the calculator functions🤗.
* [ ] Every number divided by 0 is undefined, currently the applications throws into error.
- Here is how we can handle this issue, you have to return ```undefine```
* [ ] When a long number is entered, they disappear from the screen.
- Here is how we handle it, the number should not be hidden when it overflows, but you could break in such a way all the numbers are visible or make the number decrease in size to occupy more space and be available to the user all times

**[OPTIONAL]**
* [ ] Continuous operation like 7+7+7 fails to output the right result after we enter the equal sign.
- Here is how you can handle this issue, make sure whenever an operator is selected and num1 and num1 exist, the operation should trigger computation, so we can keep operating on the inputs.
* [ ] Make it a habit to always add a description to every repo you create on Github
### That is it Kindly make the changes and submit a re-review🤗.
#### Happy coding👨‍💻 
Addo Forison

2020-07-31 08:43 UTC, expjazz commented
- [ ] Fixed bug of long numbers

![image](https://user-images.githubusercontent.com/61479648/89016453-26e85b00-d2ef-11ea-9a55-2471cb4f8b4d.png)

- [ ] fixed bug of division by zero

![image](https://user-images.githubusercontent.com/61479648/89016496-35cf0d80-d2ef-11ea-9b13-54234cca63a7.png)

- [ ] add continuos operations.

2020-08-02 00:38 UTC, jofer86 approved these changes
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- It all appears to be in order, the changes requested were met!! you might move along now.

## `const STATUS= "Approved"` 🚀 🚀 🚀 

--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2023-03-20 11:35 UTC, closed without merging